image: docker:24.0.7

services:
  - docker:24.0.7-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main

test:
  stage: test
  image: $IMAGE_TAG
  services:
    - mysql:8.0
  variables:
    DB_HOST: mysql
    DB_DATABASE: akaunting_test
    DB_USERNAME: root
    DB_PASSWORD: akaunting
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate --force
    - php artisan test
  only:
    - main

deploy:
  stage: deploy
  image: alpine:3.20
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "
        cd /path/to/your/project &&
        git pull &&
        docker-compose pull &&
        docker-compose up -d --build &&
        docker exec $APP_CONTAINER php artisan migrate --force
      "
  only:
    - main
