version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akaunting_app
    volumes:
      - ./app:/var/www
      - ./app/storage:/var/www/storage
      - ./app/public:/var/www/public
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: akaunting_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: akaunting_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: akaunting
      MYSQL_USER: akaunting
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
